name: login_deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      S_NAME: ${{ secrets.YANDEX_SERVER_NAME }}
      S_PASSWORD: ${{ secrets.YANDEX_SSH }}
    steps:
      - uses: actions/checkout@v3

      - uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.YANDEX_SSH }}
          known_hosts: ${{ secrets.YANDEX_HOST }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Build linux
        run: env CGO_ENABLED=0 go build -o deployments/auth-api/halva-login cmd/halva-auth-api/main.go

      - name: Build windows
        run: env CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o windows/halva-login.exe cmd/halva-auth-api/main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: halva-login
          path: windows/halva-login.exe
          retention-days: 5

      - name: Deploy
        run: |
          rsync -avze "ssh -o StrictHostKeyChecking=no" deployments/auth-api/* "$S_NAME":/home/halva/services/auth-api/
          ssh -o StrictHostKeyChecking=no "$S_NAME" /home/halva/services/auth-api/restart.sh
