name: music_deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      S_NAME: ${{ secrets.YANDEX_SERVER_NAME }}
      S_PASSWORD: ${{ secrets.YANDEX_SSH }}
    steps:
      - uses: actions/checkout@v3

      - uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.YANDEX_SSH }}
          known_hosts: ${{ secrets.YANDEX_HOST }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Build linux
        run: go build -o deployments/discord-music/halva-music cmd/halva-discord-music/main.go

      - name: Build windows
        run: env GOOS=windows GOARCH=amd64 go build -o windows/halva-music.exe cmd/halva-discord-music/main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: halva-music
          path: windows/halva-music.exe
          retention-days: 5

      - name: Deploy
        run: |
          rsync -avze "ssh -o StrictHostKeyChecking=no" deployments/discord-music/* "$S_NAME":/home/halva/services/discord-music/
          ssh -o StrictHostKeyChecking=no "$S_NAME" /home/halva/services/discord-music/restart.sh
